Create lr-zerlegung
it22sum/useful-numerical-math-scripts pull request #54
Opened 2024-01-11 08:09 UTC by Newoss

LR-Zerlegung mit pivot hinzugefügt

2024-01-11 08:11 UTC, Newoss commented
@yhlbr und @sebi-buchmann habt ihr eine Idee warum scipy bei der LU-Zerlegung die Pivotmatrix falsch ausgibt und man das Inverse bilden muss...

2024-01-13 10:36 UTC, yhlbr requested changes
Der rest finde ich gut, aber keine Ahnung warum man die inverse machen muss

2024-01-13 10:36 UTC, yhlbr commented on scripts/kap4/lr-zerlegung
> +lu = scipy.linalg.lu(A)
```suggestion
[p,l,r] = scipy.linalg.lu(A)  
```
fände ich schöner

plus .py extension evtl?

2024-01-14 10:03 UTC, fiechdus approved these changes

2024-01-14 10:04 UTC, fiechdus approved these changes

2024-01-14 10:04 UTC, fiechdus approved these changes

2024-01-14 10:53 UTC, yhlbr approved these changes

2024-01-14 10:53 UTC, merged